name: .NET

on:
  workflow_call:
    outputs:
      firstword:
        description: "Version as determined by GitVersion"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        updateAssemblyInfo: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup Bin Cache
      uses: actions/cache@v2
      with:
        path: ./bin
        key: bin-${{ github.sha }}

    - name: Setup Obj Cache
      uses: actions/cache@v2
      with:
        path: ./obj
        key: obj-${{ github.sha }}

    - name: Restore dependencies
      run: dotnet restore   

    - name: Build
      run: dotnet build --no-restore
      
