name: NuGet Release

on:
  workflow_call:    
    secrets:
      NUGET_TOKEN:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get Bin Cache
        uses: actions/cache@v2
        with:
          path: ./bin
          key: bin-${{ github.sha }}

      - name: Get Obj Cache
        uses: actions/cache@v2
        with:
          path: ./obj
          key: obj-${{ github.sha }}
      
      - name: Pack
        run: dotnet pack -o ./nuget --no-build

      - name: Push
        run: dotnet nuget push ./nuget/$(ls ./nuget) --api-key "${{ secrets.NUGET_TOKEN }}" --source https://api.nuget.org/v3/index.json