name: NuGet Release

on:
  workflow_call:    
    secrets:
      NUGET_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get Bin Cache
        uses: actions/cache@v3
        with:
          path: ./bin
          key: bin-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Get NuGet Cache
        uses: actions/cache@v3
        with:
          path: ./nuget
          key: nuget-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Push
        run: dotnet nuget push ./nuget/$(ls ./nuget) --api-key "${{ secrets.NUGET_TOKEN }}" --source https://api.nuget.org/v3/index.json